version: "3.9"

services:

  database:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=movies
      - POSTGRES_USER=dm3tr0
      - POSTGRES_PASSWORD=123

  web:
    env_file:
      .env
    build:
      context: .
    image: "bigasshmwork-web-1"
    volumes:
      - .:/src
      - static:/static
    tty: true
    environment:
      - DB_HOST=database
      - DB_NAME=movies
      - DB_USER=dm3tr0
      - DB_PASS=123
      - DB_PORT=5432
      - POSTGRES_NAME=movies
      - POSTGRES_USER=dm3tr0
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=project.settings


    depends_on:
      - database

  nginx:
    image: nginx:latest
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./static_cdn:/static
   depends_on:
      - web

volumes:
  pgdata:
  static:

