version: "3.9"

services:

  database:
      image: postgres:15.1
      environment:
        - POSTGRES_NAME=movies
        - POSTGRES_USER=dm3tr0
        - POSTGRES_PASSWORD=123

  web:
    env_file:
      .env
    build:
      context: .
    image: "bigasshmwork-web-1"
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    tty: true
    environment:
      - DB_HOST=database
      - DB_NAME=movies
      - DB_USER=dm3tr0
      - DB_PASS=123
      - DB_PORT=5432
      
      - POSTGRES_NAME=movies
      - POSTGRES_USER=dm3tr0
      - POSTGRES_PASSWORD=postgres
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      sh -c "python manage.py migrate"

    depends_on:
      - database

