# Generated by Django 3.2.6 on 2023-02-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=256)),
                ('title_type', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('adult', models.BooleanField()),
                ('year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('imdb_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('birthday', models.CharField(max_length=10)),
                ('deathday', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PersonMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('category', models.CharField(max_length=256)),
                ('job', models.CharField(max_length=256)),
                ('chars', models.CharField(max_length=256)),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=256)),
                ('date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'movies_comment',
            },
        ),
    ]
