# Generated by Django 4.1.4 on 2023-03-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='literal_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='pic',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='literal_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='rates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='deathday',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='category',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='chars',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='job',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='mid',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='personmovie',
            name='pid',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='RateMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=256)),
                ('person', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
                ('personmovie', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='movies.personmovie')),
            ],
        ),
    ]
